### ISSUE TITLE
Zoomwintab.vim + toggleterm.nvim causes cursor position to be lost on ZoomWinTabOut

### ISSUE THREAD

**Issue by ColinKennedy** [troydm/zoomwintab.vim#15]
This issue does not occur with a regular terminal buffer that I can see and may be related to https://github.com/akinsho/toggleterm.nvim/issues/516.

If you make a toggleterm buffer, scroll up inside of it while in `NORMAL` mode, then call `:ZoomWinTabToggle` twice (once to zoom in and once to go back to the unzoomed window), the cursor position is lost.

You can see it here, with this minimal lua reproduction.

<details>
<summary>Click to expand</summary>

```lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {'akinsho/toggleterm.nvim', version = "*", config = true},
  {
      -- Note: This plugin needs to load on-start-up I think. You can't defer-load it.
      "troydm/zoomwintab.vim",
  },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})
```
</details>

### Bug Demo
https://github.com/troydm/zoomwintab.vim/assets/10103049/07f8fc6d-9837-4fef-874d-0e0dc2ca2911

**Comment by troydm** [comment]
@ColinKennedy thank you for the fix

**Comment by ColinKennedy** [comment]
Thank you for the quick review and merge :)!
