### ISSUE TITLE
Make zoomwintab work with empty buffer

### ISSUE THREAD

**Issue by AnthonyAstige** [troydm/zoomwintab.vim#5]
![image](https://user-images.githubusercontent.com/236039/34469580-42f66462-eed7-11e7-9b5e-0b9e96aa13c3.png)

https://github.com/neovim/neovim/issues/997#issuecomment-150844269

**Comment by troydm** [comment]
@AnthonyAstige please grab latest version and check if it works for you now

**Comment by AnthonyAstige** [comment]
@troydm Awesome it works, thanks! :)
