### ISSUE TITLE
Support for sessions?

### ISSUE THREAD

**Issue by bedax** [troydm/zoomwintab.vim#6]
First of all, thank you for this plugin, it's very useful. However, it doesn't seem to save the toggle information across sessions. So if I `:ZoomWinTabToggle` to maximise, then close and reload the session, `:ZoomWinToggle` no longer restores the original layout.

It may be worth mentioning that I'm using vim-obsession to manage sessions, but I doubt it's affecting anything here.

**Comment by troydm** [comment]
@bedax I'm not sure how vim-obsession works but I can tell you that zoomwintab is essentially quick and dirty hack and by no means something that follows vim's internal workflow, when window is zoomed there is actually local tab variable written to t:zoomwintab to indicate that tab is used for zoomed window. If you can investigate how vim-obsession saves and handles state you might be able to add vim-obsession related support and then make a pull request. If you don't know where to start I suggest you start with this http://learnvimscriptthehardway.stevelosh.com/ helpful guide for learning viml

**Comment by bedax** [comment]
@troydm As far as I know, vim-obsession basically just automates calls to `:mksession`, so I don't think it's doing anything special to the session files. I've tried setting `set sessionoptions+=localoptions` but that doesn't seem to work, though from your description it sounds like it should, so I'm not sure. I'll keep looking into it though, Thanks for getting back to me.
`

**Comment by bedax** [comment]
@Asheq yeah that's what I've been doing. I had wanted it to restore to how it was, but I think I was being fussy. I've got used to how it works now, plus it doesn't happen very often. I think this issue may as well be closed. Thanks
