### ISSUE TITLE
Zoom toggle status

### ISSUE THREAD

**Issue by jmolero** [troydm/zoomwintab.vim#9]
Thanks for this plugin. 

Would it be possible to add some kind of feedback to know if we are currently in a zoomed window? I'd prefer if airline is used for this.

**Comment by troydm** [comment]
@jmolero added support and opened vim airline extension PR https://github.com/vim-airline/vim-airline/pull/2111, will close this issue when PR will be merged into vim airline

**Comment by kazukazuinaina** [comment]
@jmolero , @troydm 

#11 's patch may resolve this issue.
Could you check this PR?

**Comment by troydm** [comment]
PR is merged, reopen this issue if it won't work for you
